### ISSUE TITLE
Test Failure : admin view flow non-authenticated user

### ISSUE THREAD

**Issue by Svjard** [Svjard/sagedesk#25]
Not forwarding to login screen if no user is authenticated.

**Comment by Svjard** [comment]
Message:
    Expected -1 not to be -1.
  Stack:
    Error: Failed expectation
        at /home/marc/Workspace/sagedesk.bak/src/client/js/components/Admin.e2e.js:23:45
        at Array.forEach (native)
        at process._tickCallback (node.js:366:9)
